CREATE DATABASE catalog_of_my_things;

CREATE TABLE item(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    genre VARCHAR(50),
    author VARCHAR(50),
    label VARCHAR(50),
    publish_date DATE,
    archived BOOLEAN
);

CREATE TABLE book(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    publisher VARCHAR(50),
    cover_state VARCHAR(50)
);

CREATE TABLE label(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(50),
    color VARCHAR(50),
    item_id INT FOREIGN KEY REFRENCES item(id)
)

CREATE TABLE author (
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(20),
	last_name VARCHAR(20),
    item_id INT FOREIGN KEY REFRENCES item(id)
);

CREATE TABLE game(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	last_played_at DATE,
	multiplayer BOOLEAN
);

CREATE TABLE genre(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50)
    item_id INT FOREIGN KEY REFRENCES item(id)
)

CREATE TABLE music_album(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    on_spotify BOOLEAN
)
