require_relative '../genre/genre'
require_relative '../album/music_album'
require_relative '../label/label'
require_relative '../book/book'
require_relative '../game/game'
require_relative '../author/author'
require_relative '../item'
